exports('getServerFramework', function() return it.framework end)
exports('getServerInventory', function() return it.inventory end)
exports('getServerInteraction', function() return it.interaction end)
exports('getServerNotify', function() return it.notify end)
exports('getServerTextUI', function() return it.textUI end)
exports('getServerMenu', function() return it.menu end)
exports('getServerDisptach', function() return it.dispatch end)