RegisterNetEvent('bridge_tester:client:notifyTest', function()
    exports.it_bridge:SendNotification('Success', 'This is a success notification', 5000, 'Success', false)
    Wait(5000)
    exports.it_bridge:SendNotification('Info', 'This is an info notification', 5000, 'Info', false)
    Wait(5000)
    exports.it_bridge:SendNotification('Error', 'This is an error notification', 5000, 'Error', false)
    Wait(5000)
    exports.it_bridge:SendNotification('Warning', 'This is an Warning notification', 5000, 'Warning', false)
end)